/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Whisky } from "./Whisky";
export * as factories from "./factories";
export { Whisky__factory } from "./factories/Whisky__factory";
